apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "debian"
spec:
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
  source:
    http:
      url: "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.raw"
