---
roles: 
  - name: xanmanning.k3s
    version: v3.4.4
  - name: githubixx.iscsi_target
    version: 2.0.0
  - name: githubixx.ansible_role_wireguard
    version: 16.0.2
  - name: robertdebock.kubectl
    version: 2.1.5
  - name: robertdebock.update
    version: 3.1.8
  - name: robertdebock.terraform
    version: 4.1.7
  - name: geerlingguy.helm
    version: 1.0.1
collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: community.general
  - name: community.libvirt
    version: 1.3.0
  - name: kubernetes.core
    version: 3.0.1
  - name: containers.podman
    version: 1.13.0
  - name: devsec.hardening
    version: 9.0.1
  - name: kubevirt.core
    version: 1.3.2
