lab_nas:
  hosts:
    nasbo:

cockpit_vmhost:
  children:
    lab_nas:
  hosts:
    ronny-1:

nasbo_k8s_nodes:
  hosts:
    ksmall-1:
      k3s_control_node: true
    ksmall-2:
      k3s_control_node: true
    ksmall-3:
      k3s_control_node: true

ronny_1_k8s_nodes:
  hosts:
    kmedium-1:
    kmedium-2:
    kmedium-3:

k8s_nodes:
  children:
    nasbo_k8s_nodes:
    ronny_1_k8s_nodes:

k3s_nodes:
  children:
    k8s_nodes:
