lab_nas:
  hosts:
    nasbo:

cockpit_vmhost:
  children:
    lab_nas:
    ronny_nodes:

nasbo_k8s_nodes:
  hosts:

ronny_nodes:
  hosts:
    ronny-1:
      armlab_guest_list: ronny_1_k8s_nodes
    ronny-2:
      armlab_guest_list: ronny_2_k8s_nodes
    ronny-3:
      armlab_guest_list: ronny_3_k8s_nodes

ronny_1_k8s_nodes:
  hosts:
    ksmall-1:
      k3s_control_node: true
      armlab_instance_type: ksmall
    kmedium-1:
      armlab_instance_type: kmedium

ronny_2_k8s_nodes:
  hosts:
    ksmall-2:
      armlab_instance_type: ksmall
      k3s_control_node: true
    kmedium-2:
      armlab_instance_type: kmedium

ronny_3_k8s_nodes:
  hosts:
    ksmall-3:
      armlab_instance_type: ksmall
      k3s_control_node: true
    kmedium-3:
      armlab_instance_type: kmedium

k8s_nodes:
  children:
    ronny_1_k8s_nodes:
    ronny_2_k8s_nodes:
    ronny_3_k8s_nodes:

k3s_nodes:
  children:
    k8s_nodes:
