---
- hosts:
    - ronny_nodes
  strategy: free

  tasks:
    - name: destroy ronny_1 k8s vms
      include_role:
        name: lanefu.armlab.destroy_kvm_guest
      vars:
        destroy_item: "{{ item }}"
      loop: "{{ groups[armlab_guest_list]}}"
      tags:
        - destroy
        - kvm
