---
- hosts: "{{ hypervisor_host | default('ronny-1') }}"
  tasks:
    - name: "Destroy VM: {{ test_vm_hostname | default('router-test-1') }}"
      include_role:
        name: lanefu.armlab.destroy_kvm_guest
      vars:
        destroy_item: "{{ test_vm_hostname | default('router-test-1') }}"
