---
- hosts:
    - k8s_nodes
  gather_facts: no
  tasks:
    - name: local resolver fallback reminder
      debug:
        msg: "if a newly provisioned node only fails locally, you may need to flush mDNS with sudo killall -HUP mDNSResponder"
    - name: Wait for nodes to be online
      ansible.builtin.wait_for_connection:
