---
- hosts: ronny-1
  vars_files:
    - ../vars/armlab_vm_defaults.yml
    - ../vars/local.yml
  tasks:
    - name: provision test-router-1
      include_role:
        name: lanefu.armlab.provision_kvm_guest
      vars:
        provision_kvm_guest_hostname: "{{ test_vm_hostname }}"
        provision_kvm_guest_machine_folder: /mnt/cheapo/machines/router_lab
        provision_kvm_guest_image_file: "{{ test_vm_hostname }}.img.qcow2"
        provision_kvm_guest_image_size: 20G
        provision_kvm_guest_smp: 2
        provision_kvm_guest_memory: 2048
        provision_kvm_guest_mac_address: "{{ test_vm_mac }}"
        provision_kvm_guest_instance_id: "{{ test_vm_hostname }}{{ provision_kvm_guest_instance_id_suffix }}"
