---
- hosts:
    - ronny_nodes
  strategy: free
  vars_files:
    - ../vars/armlab_vm_defaults.yml
    - ../vars/local.yml
  vars:
    armlab_instance_type:
      ksmall:
        size: 25G
        smp: 2
        memory: 2000
      kmedium:
        size: 40G
        smp: 4
        memory: 4000
      klarge:
        size: 60G
        smp: 6
        memory: 6000
      kxlarge:
        size: 80G
        smp: 8
        memory: 8000

  tasks:
    - name: build ronny k8s vms
      include_role:
        name: lanefu.armlab.provision_kvm_guest
      vars:
        provision_kvm_guest_hostname: "{{ item }}"
        provision_kvm_guest_machine_folder: "{{ provision_kvm_guest_machine_folder_k8s }}"
        provision_kvm_guest_image_size: "{{ armlab_instance_type[hostvars[item].armlab_instance_type].size }}"
        provision_kvm_guest_smp: "{{ armlab_instance_type[hostvars[item].armlab_instance_type].smp }}"
        provision_kvm_guest_memory: "{{ armlab_instance_type[hostvars[item].armlab_instance_type].memory }}"
        provision_kvm_guest_instance_id: "{{ item ~ provision_kvm_guest_instance_id_suffix }}"
      loop: "{{ groups[armlab_guest_list] }}"
      tags:
        - provision
        - kvm
