---
- hosts:
    - ronny_nodes
  strategy: free
  vars:
    armlab_instance_type:
      ksmall:
        size: 25G
        smp: 2
        memory: 2000
      kmedium:
        size: 40G
        smp: 4
        memory: 4000
      klarge:
        size: 60G
        smp: 6
        memory: 6000
      kxlarge:
        size: 80G
        smp: 8
        memory: 8000

  tasks:
    - name: build ronny_k8s vms
      include_role:
        name: lanefu.armlab.provision_kvm_guest
      vars:
        item_instance_type: "{{ hostvars[item].armlab_instance_type }}"
        armlab_provision_image_folder: /mnt/cheapo/images
        armlab_provision_machine_folder: /mnt/cheapo/machines/ktest
        armlab_provision_image_size: "{{ armlab_instance_type[item_instance_type]['size'] }}"
        #armlab_provision_base_image: Armbian-unofficial_24.07.22-armsurvivors-364_Uefi-arm64_bookworm_edge_6.9.10-metadata-cloud.img.qcow2
        #armlab_provision_base_image: debian-13-generic-arm64-daily.qcow2
        armlab_provision_base_image: debian-12-generic-arm64-daily.qcow2
        armlab_provision_smp: "{{ armlab_instance_type[item_instance_type]['smp'] }}"
        armlab_provision_memory: "{{ armlab_instance_type[item_instance_type]['memory'] }}"
        armlab_provision_hostname: "{{ item }}"
      loop: "{{ groups[armlab_guest_list] }}"
      tags:
        - provision
        - kvm
