---
- hosts:
    - ronny_nodes
  strategy: free
  vars:
    armlab_instance_type:
      ksmall:
        size: 25G
        smp: 2
        memory: 2000
      kmedium:
        size: 40G
        smp: 4
        memory: 4000
      klarge:
        size: 60G
        smp: 6
        memory: 6000
      kxlarge:
        size: 80G
        smp: 8
        memory: 8000

  tasks:
    - name: build ronny_k8s vms
      include_role:
        name: lanefu.armlab.provision_kvm_guest
      vars:
        item_instance_type: "{{ hostvars[item].armlab_instance_type }}"
        provision_kvm_guest_image_folder: /mnt/cheapo/images
        provision_kvm_guest_machine_folder: /mnt/cheapo/machines/ktest
        provision_kvm_guest_image_size: "{{ armlab_instance_type[item_instance_type]['size'] }}"
        # provision_kvm_guest_base_image: Armbian_25.8.0-trunk.325_Uefi-arm64_trixie_cloud_6.12.36_minimal.img.qcow2
        provision_kvm_guest_base_image: debian-13-generic-arm64-daily.qcow2
        # provision_kvm_guest_base_image: debian-12-generic-arm64-daily.qcow2
        # provision_kvm_guest_base_image: armbian_cloud.img.qcow2
        provision_kvm_guest_smp: "{{ armlab_instance_type[item_instance_type]['smp'] }}"
        provision_kvm_guest_memory: "{{ armlab_instance_type[item_instance_type]['memory'] }}"
        provision_kvm_guest_hostname: "{{ item }}"
      loop: "{{ groups[armlab_guest_list] }}"
      tags:
        - provision
        - kvm
